---

- hosts: all
  become: true
  pre_tasks:

  - name: Update and Upgrade (Ubuntu Sever)
    apt:
      update_cache: yes
      upgrade: dist
    when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  tasks:

  - name: Install Docker (Ubuntu)
    apt:
      name:
        - docker.io
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"


- hosts: db_servers
  become: true
  tasks:

  - name: Install Docker (Ubuntu)
    apt:
      name:
        - docker.io
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

